; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

	TITLE	D:\git\c\Algo\rsa\print.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG3046	DB	'%s', 0aH, 00H
_DATA	ENDS
PUBLIC	_prints
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_s$ = 8							; size = 4
_prints	PROC
; File d:\git\c\algo\rsa\print.c
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	mov	eax, DWORD PTR _s$[ebp]
	push	eax
	push	OFFSET $SG3046
	call	_printf
	add	esp, 8
; Line 6
	pop	ebp
	ret	0
_prints	ENDP
_TEXT	ENDS
END
